// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lghddbepbmotwdyjyjem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnaGRkYmVwYm1vdHdkeWp5amVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTc4MzQsImV4cCI6MjA3MDkzMzgzNH0.KALylre-KbyFvE0txYXTHQcJsZlP4MAY4iJYg0GZWoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});